# Generated by Django 3.1.7 on 2021-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=10)),
                ('time', models.IntegerField(default=10)),
                ('service', models.CharField(max_length=20)),
            ],
        ),
    ]
